# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shippost < Formula
  desc "Post to X from your terminal with AI-powered suggestions from git commits"
  homepage "https://github.com/tomswokowski/shippost"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomswokowski/shippost/releases/download/v0.0.1/shippost_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "1679779b92fb604f9b8d5a33e146999573665bdd337b0b7cf2ecf9dc53dd7b98"

      def install
        bin.install "shippost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomswokowski/shippost/releases/download/v0.0.1/shippost_0.0.1_Darwin_arm64.tar.gz"
      sha256 "05cc8b08b8e50afa0d95a380dd3e313ec4c8bc84fcb94c28bf1f5dd594df652c"

      def install
        bin.install "shippost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomswokowski/shippost/releases/download/v0.0.1/shippost_0.0.1_Linux_x86_64.tar.gz"
      sha256 "f0e12f032af2d83e0414cfd77035b7e0ef5a616891dbcd2a9f040bae7cc5434b"
      def install
        bin.install "shippost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomswokowski/shippost/releases/download/v0.0.1/shippost_0.0.1_Linux_arm64.tar.gz"
      sha256 "f45a0062acd2f990b978dd38995e4b2ca3d3d5b9882293866e846f66685790d9"
      def install
        bin.install "shippost"
      end
    end
  end

  test do
    system "#{bin}/shippost --version"
  end
end
