# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shippost < Formula
  desc "Post to X from your terminal with AI-powered suggestions from git commits"
  homepage "https://github.com/tomswokowski/shippost"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomswokowski/shippost/releases/download/v0.0.1/shippost_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "4620b19dd2d01df110609043aa9560e16ce9d4aa1af668fa9bc73db937dfd1f7"

      def install
        bin.install "shippost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomswokowski/shippost/releases/download/v0.0.1/shippost_0.0.1_Darwin_arm64.tar.gz"
      sha256 "f0ad452e1b49d3ed2c39cfba80abc06412e9e54677239b36994b3de4e26b421c"

      def install
        bin.install "shippost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomswokowski/shippost/releases/download/v0.0.1/shippost_0.0.1_Linux_x86_64.tar.gz"
      sha256 "e80cee8eb00f509ba31d1d2feff270dc843ccf671282227009e6e402c0009b85"
      def install
        bin.install "shippost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomswokowski/shippost/releases/download/v0.0.1/shippost_0.0.1_Linux_arm64.tar.gz"
      sha256 "703277bf3c36742801f0d42d275ac49838f6c10e7df0e2dea098776e2bd8aba7"
      def install
        bin.install "shippost"
      end
    end
  end

  test do
    system "#{bin}/shippost --version"
  end
end
