# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shippost < Formula
  desc "Post to X from your terminal with AI-powered suggestions from git commits"
  homepage "https://github.com/tomswokowski/shippost"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomswokowski/shippost/releases/download/v0.0.1/shippost_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "f53b3e224c428241a0620b79e91ff1bf4acb00d78c748d1426162507c4b95b81"

      def install
        bin.install "shippost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomswokowski/shippost/releases/download/v0.0.1/shippost_0.0.1_Darwin_arm64.tar.gz"
      sha256 "c1bef835270606b174f1c971eb10bae77d6a1ffe753a9e3ea90cfacacef63a2f"

      def install
        bin.install "shippost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomswokowski/shippost/releases/download/v0.0.1/shippost_0.0.1_Linux_x86_64.tar.gz"
      sha256 "c27bc080fb6814c4a7310f44a77db2c4b362a7e89dd32e7108426c230d7b4021"
      def install
        bin.install "shippost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomswokowski/shippost/releases/download/v0.0.1/shippost_0.0.1_Linux_arm64.tar.gz"
      sha256 "74559fe72c05dc6efcadf42fd1f22b1814a44ea582e2c4432b4943922e02159f"
      def install
        bin.install "shippost"
      end
    end
  end

  test do
    system "#{bin}/shippost --version"
  end
end
